//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDB_ImageGallery
{
    using System;
    using System.Collections.Generic;
    
    public partial class Photo
    {
        public int photo_id { get; set; }
        public string photo_path { get; set; }
        public int account_id { get; set; }
        public int category_id { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Category Category { get; set; }
    }
}
